#include "Constants.h"

namespace p3d {
    unsigned int getVecFormatSizeBits(P3D_VECTOR_FORMAT format) {
        switch (format) {
            case P3D_FORMAT_UNKNOWN:
                return 0;
            case P3D_FORMAT_R32G32B32A32_TYPELESS:
                return 128;
            case P3D_FORMAT_R32G32B32A32_FLOAT:
                return 128;
            case P3D_FORMAT_R32G32B32A32_UINT:
                return 128;
            case P3D_FORMAT_R32G32B32A32_SINT:
                return 128;
            case P3D_FORMAT_R32G32B32_TYPELESS:
                return 96;
            case P3D_FORMAT_R32G32B32_FLOAT:
                return 96;
            case P3D_FORMAT_R32G32B32_UINT:
                return 96;
            case P3D_FORMAT_R32G32B32_SINT:
                return 96;
            case P3D_FORMAT_R16G16B16A16_TYPELESS:
                return 64;
            case P3D_FORMAT_R16G16B16A16_FLOAT:
                return 64;
            case P3D_FORMAT_R16G16B16A16_UNORM:
                return 64;
            case P3D_FORMAT_R16G16B16A16_UINT:
                return 64;
            case P3D_FORMAT_R16G16B16A16_SNORM:
                return 64;
            case P3D_FORMAT_R16G16B16A16_SINT:
                return 64;
            case P3D_FORMAT_R32G32_TYPELESS:
                return 64;
            case P3D_FORMAT_R32G32_FLOAT:
                return 64;
            case P3D_FORMAT_R32G32_UINT:
                return 64;
            case P3D_FORMAT_R32G32_SINT:
                return 64;
            case P3D_FORMAT_R32G8X24_TYPELESS:
                return 64;
            case P3D_FORMAT_D32_FLOAT_S8X24_UINT:
                return 64;
            case P3D_FORMAT_R32_FLOAT_X8X24_TYPELESS:
                return 64;
            case P3D_FORMAT_X32_TYPELESS_G8X24_UINT:
                return 64;
            case P3D_FORMAT_R10G10B10A2_TYPELESS:
                return 32;
            case P3D_FORMAT_R10G10B10A2_UNORM:
                return 32;
            case P3D_FORMAT_R10G10B10A2_UINT:
                return 32;
            case P3D_FORMAT_R11G11B10_FLOAT:
                return 32;
            case P3D_FORMAT_R8G8B8A8_TYPELESS:
                return 32;
            case P3D_FORMAT_R8G8B8A8_UNORM:
                return 32;
            case P3D_FORMAT_R8G8B8A8_UNORM_SRGB:
                return 32;
            case P3D_FORMAT_R8G8B8A8_UINT:
                return 32;
            case P3D_FORMAT_R8G8B8A8_SNORM:
                return 32;
            case P3D_FORMAT_R8G8B8A8_SINT:
                return 32;
            case P3D_FORMAT_R16G16_TYPELESS:
                return 32;
            case P3D_FORMAT_R16G16_FLOAT:
                return 32;
            case P3D_FORMAT_R16G16_UNORM:
                return 32;
            case P3D_FORMAT_R16G16_UINT:
                return 32;
            case P3D_FORMAT_R16G16_SNORM:
                return 32;
            case P3D_FORMAT_R16G16_SINT:
                return 32;
            case P3D_FORMAT_R32_TYPELESS:
                return 32;
            case P3D_FORMAT_D32_FLOAT:
                return 32;
            case P3D_FORMAT_R32_FLOAT:
                return 32;
            case P3D_FORMAT_R32_UINT:
                return 32;
            case P3D_FORMAT_R32_SINT:
                return 32;
            case P3D_FORMAT_R24G8_TYPELESS:
                return 32;
            case P3D_FORMAT_D24_UNORM_S8_UINT:
                return 32;
            case P3D_FORMAT_R24_UNORM_X8_TYPELESS:
                return 32;
            case P3D_FORMAT_X24_TYPELESS_G8_UINT:
                return 32;
            case P3D_FORMAT_R8G8_TYPELESS:
                return 16;
            case P3D_FORMAT_R8G8_UNORM:
                return 16;
            case P3D_FORMAT_R8G8_UINT:
                return 16;
            case P3D_FORMAT_R8G8_SNORM:
                return 16;
            case P3D_FORMAT_R8G8_SINT:
                return 16;
            case P3D_FORMAT_R16_TYPELESS:
                return 16;
            case P3D_FORMAT_R16_FLOAT:
                return 16;
            case P3D_FORMAT_D16_UNORM:
                return 16;
            case P3D_FORMAT_R16_UNORM:
                return 16;
            case P3D_FORMAT_R16_UINT:
                return 16;
            case P3D_FORMAT_R16_SNORM:
                return 16;
            case P3D_FORMAT_R16_SINT:
                return 16;
            case P3D_FORMAT_R8_TYPELESS:
                return 8;
            case P3D_FORMAT_R8_UNORM:
                return 8;
            case P3D_FORMAT_R8_UINT:
                return 8;
            case P3D_FORMAT_R8_SNORM:
                return 8;
            case P3D_FORMAT_R8_SINT:
                return 8;
            case P3D_FORMAT_A8_UNORM:
                return 8;
            case P3D_FORMAT_R1_UNORM:
                return 1;
            case P3D_FORMAT_R8G8_B8G8_UNORM:
                return 32;
            case P3D_FORMAT_G8R8_G8B8_UNORM:
                return 32;
            case P3D_FORMAT_B8G8R8A8_UNORM:
                return 32;
            case P3D_FORMAT_B8G8R8X8_UNORM:
                return 32;
            case P3D_FORMAT_B8G8R8A8_TYPELESS:
                return 32;
            case P3D_FORMAT_B8G8R8A8_UNORM_SRGB:
                return 32;
            case P3D_FORMAT_B8G8R8X8_TYPELESS:
                return 32;
            case P3D_FORMAT_B8G8R8X8_UNORM_SRGB:
                return 32;

            default:
                return 0;
        }
    }
}